### ISSUE TITLE
BKPeriphial Protocol 

### ISSUE THREAD

**Issue by kswain1** [rasmusth/BluetoothKit#10]
I am following the example of setting up a peripheral, and I am stuck when adding the BKPeriphial to my view controller class. How do I implement the BKPeriphialController Protocol?

**Comment by rasmusth** [comment]
Hi kswain1.

There is nothing in the framework called BKPeripheralController Protocol. What exactly are you referring to?

**Comment by kswain1** [comment]
I had to add the BKPeripheralDelegate functions below to use a peripheral object in my class  

 // MARK: BKPeripheralDelegate
    
    internal func peripheral(peripheral: BKPeripheral, remoteCentralDidConnect remoteCentral: BKRemoteCentral) {
        Logger.log("Remote central did connect: \(remoteCentral)")
        sendDataBarButtonItem.enabled = true
    }
    
    internal func peripheral(peripheral: BKPeripheral, remoteCentralDidDisconnect remoteCentral: BKRemoteCentral) {
        Logger.log("Remote central did disconnect: \(remoteCentral)")
        sendDataBarButtonItem.enabled = false
    }
