### ISSUE TITLE
Scanning for identifier other than UUID

### ISSUE THREAD

**Issue by aakashs** [rasmusth/BluetoothKit#14]
Hi

Would it be possible to scan for an identifer other than the device UUID? For example, I was thinking about keying off of the user's phone number. Would this be problematic due to security issues?

Thank you for all the help!

**Comment by rasmusth** [comment]
Hi Aakash.

Unfortunately this isn't possible due to the nature of Apple's CoreBluetooth.

**Comment by aakashs** [comment]
Interesting, thank you!
