### ISSUE TITLE
sendData from Central

### ISSUE THREAD

**Issue by dimohamdy** [rasmusth/BluetoothKit#15]
How i can send data from central?

**Comment by Xerosigma** [comment]
It would appear it is not possible with this library: https://github.com/rasmusth/BluetoothKit/issues/7

:cry:

**Comment by rasmusth** [comment]
You're welcome to implement it and send a pull request. Otherwise I will implement it sometime this month.

**Comment by dimohamdy** [comment]
i try to make it soon

**Comment by nickskull** [comment]
@rasmusth Any update on this? :)

**Comment by rasmusth** [comment]
@nickskull This has to be implemented for sure. You are more than welcome to do so, but I require that the MTU is sent from the peripheral to the central and re-used when sending from the central in order to achieve the largest possible throughput.
