### ISSUE TITLE
multiple services and characteristics

### ISSUE THREAD

**Issue by ptigas** [rasmusth/BluetoothKit#19]
From my understanding, it doesn't support multiple services UUIDs. Do you have any plans to support this in the future?

**Comment by rasmusth** [comment]
No, the idea of this library is to simplify Apple device to Apple device communication. You should model your messaging using objects instead of multiple services and characteristics. If you want to use other devices this library isn't the right fit.

**Comment by ptigas** [comment]
i see! thanks for the clarification :)
