### ISSUE TITLE
Example wrong SnapKit project path

### ISSUE THREAD

**Issue by tbechtum** [rasmusth/BluetoothKit#3]
Could not easily look at your sample project while the SnapKit project is included with a wrong path reference: There's a ../ too much. I had to copy the SnapKit into the directory above in order to be able to build. Could you resolve this?
Thanks a lot, cheers,
Thomas

**Comment by rasmusth** [comment]
Yes, I'll fix it tonight. Sorry for the inconvenience :)

**Comment by rasmusth** [comment]
@tbechtum Thanks for raising this issue. I hope you enjoy working with the project.
