### ISSUE TITLE
tvos support

### ISSUE THREAD

**Issue by matteocrippa** [rasmusth/BluetoothKit#8]
tvOS is pretty new and as far as I figured out some feature are not available (yet), but do you plan to add support for it next releases even for cocoapods auto install?

**Comment by rasmusth** [comment]
Let me look if I can add a target for that quickly.

**Comment by matteocrippa** [comment]
Yep, the unique thing is that I'm pretty aware of some functions available in iOS are disabled/removed in tvOS - https://developer.apple.com/library/prerelease/tvos/releasenotes/General/tvOS90APIDiffs/

**Comment by rasmusth** [comment]
@matteocrippa I do not have the new Apple TV yet. But this new target does build. It only supports taking the central role though, as that is all that is allowed by tvOS.

**Comment by rasmusth** [comment]
It won't work with Cocoapods. I'll have to split it into subspecs, which probably makes sense anyhow, as you'll most likely often only want to be either a peripheral or a central on one device.

**Comment by matteocrippa** [comment]
@rasmusth i'll give a try next week back work with the atv dev kit, 'll keep you posted!

**Comment by rasmusth** [comment]
@matteocrippa !

**Comment by matteocrippa** [comment]
@rasmusth i was out of office in those last few days, hopefully tomorrow i'll be back in the office

**Comment by rjgdesign** [comment]
Any update? Awesome library, would love to use it with tvOS! :)

**Comment by rasmusth** [comment]
@rjgdesign Please check out the development branch and test if it works with the tvOS target. I don't have an Apple TV.

**Comment by rasmusth** [comment]
Fixed.
